### ISSUE TITLE
User Facing Documentation and Examples

### ISSUE THREAD

**Issue by carwyn** [wundergraph/graphql-go-tools#243]
While `graphql-gateway` is very useful standalone, I think much of the utility in `graphql-go-tools` is in being able to use it in things like (as noted in the README):

* proxies
* caches
* server/client implementations

But, the Godocs alone are quite hard to get into and `graphql-gateway` in some respects is doing too much for you if you are wanting to build other things into your gateway or proxy (e.g. middlware in front of a Dgraph database in my case).

Some more user (library user) facing documentation and examples to illustrate how `graphql-go-tools` might be used to make a proxy/client/server would be very useful.

**Comment by carwyn** [comment]
Related to some of the comments in https://github.com/jensneuse/graphql-gateway/issues/4

**Comment by StevenACoffman** [comment]
If you would like to see an implementation of the Apollo Federation demo using DGraph as a backend, this branch has that: https://github.com/StevenACoffman/federation-demo/tree/dgraph-again

It uses DGraph's lambda support for the little bit of dynamic behavior required.

I would be interested in adapting this to use the recent federation gateway support to make a pure Go version of federation.

**Comment by StevenACoffman** [comment]
Comparing the two, I'm curious why the schema is different. Original:
```
type Review @key(fields: "id") {
  id: ID!
  body: String
  author: User @provides(fields: "username")
  product: Product
}

type User @extends @key(fields: "id") {
  id: ID! @external
  username: String @external
  reviews: [Review]
}

type Product @extends @key(fields: "upc") {
  upc: String! @external
  reviews: [Review]
}
```
This repository's [federation example](https://github.com/jensneuse/graphql-go-tools/blob/master/examples/federation/reviews/graph/schema.graphqls) version:
```
type Review {
    body: String!
    author: User! @provides(fields: "username")
    product: Product!
}

extend type User @key(fields: "id") {
    id: ID! @external
    username: String! @external
    reviews: [Review]
}

extend type Product @key(fields: "upc") {
    upc: String! @external
    reviews: [Review]
}
```

**Comment by jensneuse** [comment]
@StevenACoffman good question! =)
If you find a problem with different type definitions, please let me know.

**Comment by chedom** [comment]
@StevenACoffman 
Schema was taken from [here](https://github.com/99designs/gqlgen/blob/master/example/federation/reviews/graph/schema.graphqls)
@jensneuse if it's confusing I can change schema in the example.

**Comment by StevenACoffman** [comment]
Ah, fair enough ( [original is here](https://github.com/apollographql/federation-demo/blob/master/services/reviews/index.js#L5-L21) btw)! 

To clarify are `@key` and `@extends` directives supported at this point?

**Comment by chedom** [comment]
@StevenACoffman these directives are supported.
[Example](https://github.com/jensneuse/graphql-go-tools/blob/master/examples/federation/products/graph/schema.graphqls#L10) of federated schema with `@key` directive.
[Example](https://github.com/jensneuse/graphql-go-tools/blob/master/examples/federation/reviews/graph/schema.graphqls#L13) of federated schema with `@extend` directive.
Subscription operation is also supported.
