### ISSUE TITLE
engineV2 cannot parse object, with enum, in an array of an input in 1.26.1

### ISSUE THREAD

**Issue by baron-chiu** [wundergraph/graphql-go-tools#287]
After #286 was closed, I upgraded `graphql-go-tools` to `1.26.1`.

However, another regression bug surfaced. An enum in an array of the input can no longer be parsed correctly and break the graphql engine. `enum` in an object without being nested in an array is fine by the way.

With a simple query like this, where desc is an `enum`:
```graphql
query {
  allCitys(orderBy:[{name:desc}]){
    name
  }
}
```

The `graphql-go-tools` enginV2 will have an error and log the following:

```log
ERRO[0094] engine.Execute                                error="Value looks like object, but can't find closing '}' symbol"
```

It will cause the http handler to respond 500 without messages.

**Comment by jensneuse** [comment]
You could do 2 useful things.
a) open a PR to solve the bug =)
b) open a PR that adds a failing test and I'll fix it if you don't know how it can be fixed
Thanks! ;)

**Comment by bcgodev** [comment]
Thanks. I'll proceed one of the two soon.

Jens Neuse ***@***.***> 於 2021年9月24日 週五 01:39 寫道：
