### ISSUE TITLE
Pass WS initial payload from gateway to federated services

### ISSUE THREAD

**Issue by chedom** [wundergraph/graphql-go-tools#290]
Hi, for my use case it's required to pass user related information (token/id/roles) from gateway to federated services.
There are two possible options:

1. Use payload in `connection_init` message  (receiver must handle initPayload from `connection_init` message) (I prefer this option)
2. Use `Header` field from `FetchConfiguration`  (receiver must handle http header (before upgrading))

Both options aren't ready to use, they require some contribution.

@jensneuse which option would you prefer ?

**Comment by chedom** [comment]
@jensneuse I checked all my cases, and it turned out that in all cases `ws initial payload` is almost exactly the same as `Header` for the same upstream. 
In my fork, I just added sending `Header` as` ws initial Payload`. If necessary, I can create a PR, otherwise theissue can be closed.

**Comment by jensneuse** [comment]
I'm not sure I understand 100%. How would Header as ws initial payload look like?

**Comment by spetrunin** [comment]
closed with https://github.com/wundergraph/graphql-go-tools/pull/425
