### ISSUE TITLE
Oct 2021 Spec

### ISSUE THREAD

**Issue by mentat** [wundergraph/graphql-go-tools#310]
Is there plans to support the Oct. 2021 specification? https://spec.graphql.org/October2021/

Specifically repeatable directives are a key feature.

**Comment by jensneuse** [comment]
Yeah, absolutely! Do you want to step ahead?

**Comment by mentat** [comment]
I'm actually not even sure how this library can support Apollo Federation as Fed 1 includes this directive on the supergraph:

```
directive @join__type(graph: join__Graph!, key: join__FieldSet) repeatable on OBJECT | INTERFACE
```
I'd be happy to test out Fed1 pre-composed supergraphs with this library when that is supported.
