### ISSUE TITLE
Multipart request specification

### ISSUE THREAD

**Issue by cauchy2384** [wundergraph/graphql-go-tools#358]
Hello, I am trying to build apollo federation in my project using graphql-go-tools as the best go implementation of federation.

[Grapql multipart request spec](https://github.com/jaydenseric/graphql-multipart-request-spec) is essential to perform file uploads.
It is implemented by the [gqlgen](https://gqlgen.com/reference/file-upload/).

Could you please tell me if there is an example of multipart request implementation or plans to support it?

**Comment by jensneuse** [comment]
I personally would argue against using multipart GraphQL uploads. Instead, I'd upload a file to S3 and then work with the URL of the file, which is just a string.

That said, if you're interested in using graphql-go-tools with multiplart file uploads, nothing holds you off from writing an http handler that parses a multipart request and then handles an upload as well as the graphql request.

**Comment by cauchy2384** [comment]
Thank you for your response.

Anyway, uploading file via graphql is a valid option with pros & cons.

You are right, there is no issue writing a handler that works with multipart data. 
Unfortunately I can not see any easy way to route graphql reqeuest to the federated service with query and file in the multipart format.

**Comment by jensneuse** [comment]
@cauchy2384 Take this "gateway" as a starting point. It currently doesn't handle multipart, but can easily be added: https://github.com/jensneuse/graphql-go-tools/blob/bbc67ff664c8bfa283f8cab0f7f40cec1fd65831/examples/federation/gateway/http/http.go#L18

**Comment by cauchy2384** [comment]
@jensneuse thank you, that is the example I've been working with.

Unfortunately I can't find any methods for graphql.Request or engine that will add multipart file data and pass it to the federated service.

**Comment by daniil-kzn** [comment]
@cauchy2384 means that you should write your own Request, engine and etc.
I have encountered with the same problem. If you have resolved it please share you solution.

**Comment by devsergiy** [comment]
was completed via https://github.com/wundergraph/graphql-go-tools/pull/758
