### ISSUE TITLE
Remove abstractlogger from ExecutionEngineV2

### ISSUE THREAD

**Issue by tonquangtu** [wundergraph/graphql-go-tools#378]
Hi guys, here are some issues I have faced while using `abstractlogger.Logger` in the `graph-go-tools`.  Please help to assess
- The logger interface doesn't support log with context.Context. Context normally contains helpful information like request id or trace id which support to trace and debug the issue
- Each company has its own log solution, abstractlogger seems to stick to zap logger interface that seems not convenient for us to use. The engine just better throws the error outside instead of requiring logger.

Thanks

**Comment by jensneuse** [comment]
Could you extend abstract logger with your implementation? Or remove it and return meaningful errors instead? I'm not yet sure what direction to go, but open to discussion.

**Comment by schmidtw** [comment]
`abstractlogger` doesn't have a license, so that needs to be addressed for most folks to be able to consume `graphql-go-tools` today.

https://github.com/jensneuse/abstractlogger/issues/1
