### ISSUE TITLE
go mod tidy issue

### ISSUE THREAD

**Issue by schmidtw** [wundergraph/graphql-go-tools#381]
I'm running into this issue when I try to run `go mod tidy` and fetch the library:

```
go: finding module for package github.com/wundergraph/graphql-go-tools/pkg/graphql
go: found github.com/wundergraph/graphql-go-tools/pkg/graphql in github.com/wundergraph/graphql-go-tools v1.52.1
go: github.com/wundergraph/graphql-go-tools@v1.52.1 requires
	github.com/wundergraph/graphql-go-tools/examples/federation@v0.0.0-20220521142629-9fe3016fb1a7 requires
	github.com/wundergraph/graphql-go-tools@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```
I was looking around and saw [this change](https://github.com/wundergraph/graphql-go-tools/commit/77943df27d906396f4c7b5f2e74e731c419b6af9) that may have caused the issue.

**Comment by StarpTech** [comment]
Hi @schmidtw which go version are you using? If 1.17, please try with 1.18.

**Comment by schmidtw** [comment]
Thanks @StarpTech I happened to be using 1.16 in the mod file & moving to 1.18 fixed the problem.  I missed that go.mod for this project already specified 1.18.
