### ISSUE TITLE
Federated Schema Hash Race Condition

### ISSUE THREAD

**Issue by schmidtw** [wundergraph/graphql-go-tools#386]
I ran into a race condition with the schema Hash() function during building a prototype.  Specifically the issue is around this line:
https://github.com/wundergraph/graphql-go-tools/blob/be7d24d1b89d4cf46802f7cedb8422052f449f32/pkg/graphql/schema.go#L53

Below is a snippet of code showing how I'm creating the most recent engine from a collection of subgraphs:
```golang
				cfg := m.List()
				fecf := graphql.NewFederationEngineConfigFactory(cfg,
					gqlds.NewBatchFactory(),
					graphql.WithFederationHttpClient(gw.client))
				_, err := fecf.MergedSchema()
				if err != nil {
					gw.log.Error("get schema error", zap.Error(err))
					continue
				}

				dscfg, err := fecf.EngineV2Configuration()
				if err != nil {
					gw.log.Error("get engine config error", zap.Error(err))
					continue
				}
				dscfg.EnableDataLoader(true)

				engine, err := graphql.NewExecutionEngineV2(ctx, nil, dscfg)
				if err != nil {
					gw.log.Error("create engine error", zap.Error(err))
					continue
				}

				gw.mutex.Lock()
				gw.log.Info("engine updated")
				gw.engine = engine
				gw.mutex.Unlock()
```

But the problem is the hash is calculated at usage time.  So the question I have is how to solve this best.

A few ideas I have are:

1. Add an API to the engine that can be called to calculate the hash while it's mutex protected.
2. Change the hash to be a `sync.Atomic` type.
3. Wrap the Hash calculation with a mutex.

Any suggestions on something I missed or how we should fix?  I'm happy to create a PR once I know the direction.

**Comment by jensneuse** [comment]
I'd suggest that we build the hash at configuration time. I don't see why we need to compute this while handing a request. @pvormste What's your take on this?

**Comment by schmidtw** [comment]
Thanks - I crated a proposal PR for review.
