### ISSUE TITLE
Why marshal to/from json when the config appears fixed?

### ISSUE THREAD

**Issue by schmidtw** [wundergraph/graphql-go-tools#398]
Why marshal from a `graphql_datasource.Configuration` to JSON here:
https://github.com/wundergraph/graphql-go-tools/blob/e6e1a13e36eaf3a4e09a2bbd1eca3dfcb3d955d6/pkg/graphql/engine_config_v2.go#L97

Only to turn around and unmarshal the same struct from JSON here:
https://github.com/wundergraph/graphql-go-tools/blob/e6e1a13e36eaf3a4e09a2bbd1eca3dfcb3d955d6/pkg/engine/datasource/graphql_datasource/graphql_datasource.go#L241

Why the extra step?

**Comment by jensneuse** [comment]
I think Custom could also be changed to any.
