### ISSUE TITLE
Error resolving a type by a subfield of itself

### ISSUE THREAD

**Issue by genesor** [wundergraph/graphql-go-tools#404]
Hello,

We are building a Federated Gateway and we are facing an issue when trying to resolve a type using a subfield of itself.

Here is the problematic part of our schema:

```
extend type User {
  id: String! @external
}

type FriendUser @key(fields: "user { id }") {
  user: User!

  someField: Int!
  someOtherField: Int!
}
```

In a service we have an entity called `FriendUser` which embed a `User`, currently we are dynamically resolving the FriendUser using the `user.id` attribute and the Apollo Federated Gateway has no trouble resolving it but when running with our new go gateway we receive the following `operationreport.Report` error.

```
{
	"InternalErrors": [
		{
			"InternalErrors": null,
			"ExternalErrors": [
				{
					"message": "field: { not defined on type: FriendUser",
					"path": [
						"query",
						"friends",
						"user",
						"{"
					],
					"locations": null
				}
			]
		}
	],
	"ExternalErrors": [
		{
			"message": "field: { not defined on type: FriendUser",
			"path": [
				"query",
				"friends",
				"user",
				"{"
			],
			"locations": null
		}
	]
}
```

We can see that there is a problem reading the `@key fields` annotation.

Would you happen to have some kind of solution for our problem or any help ? 

Thanks

**Comment by jensneuse** [comment]
Hey, sorry for getting back this late. I was on vacation.
I'm interested in solving this problem. Could you add a test that fails, but should be green?
I'll then get someone to fix the bug or fix it myself.
Thank you!

**Comment by genesor** [comment]
Hey @jensneuse 

Thanks for the reply. I will try to add a test case for this in the coming days. 

If possible, could you please point me to the right place where the tests related to federation resolving are ?

**Comment by jensneuse** [comment]
Planner:

https://github.com/wundergraph/graphql-go-tools/blob/e6e1a13e36eaf3a4e09a2bbd1eca3dfcb3d955d6/pkg/engine/datasource/graphql_datasource/graphql_datasource_test.go#L4112

Resolver:

https://github.com/wundergraph/graphql-go-tools/blob/e6e1a13e36eaf3a4e09a2bbd1eca3dfcb3d955d6/pkg/engine/resolve/resolve_test.go#L2627

**Comment by devsergiy** [comment]
Hi @genesor 

federation example was updated, please try to use it instead of any old code
https://github.com/wundergraph/graphql-go-tools/tree/master/examples/federation
