### ISSUE TITLE
Event type removed in SSE messages

### ISSUE THREAD

**Issue by qiangfoo** [wundergraph/graphql-go-tools#427]
In a SSE subscription, when the subgraph returns `data: {"username": "bobby", "time": "02:33:48"}`, the prefix `data: ` is removed from the response. The json string `{"username": "bobby", "time": "02:33:48"}` is what's written by the engine, which I think is doing the wrong thing. It should write the event type too.

**Comment by jensneuse** [comment]
I'm not sure what the problem here is?

**Comment by qiangfoo** [comment]
@jensneuse The expectation is that the graph router should not mutate the response from subgraph.

So in this case, the subgraph returns `data: {"username": "bobby", "time": "02:33:48"}`, the router should just write the exact string to the response.

**Comment by jensneuse** [comment]
I'm not sure I understand this. What router? This is a library that can resolve federated GraphQL operations.
If you want to expose the API via SSE, you can prefix a response like this:
https://github.com/wundergraph/wundergraph/blob/2e4ae8506558165a9bf3ada4b8f45cee55a9f18d/pkg/apihandler/apihandler.go#L1405

It's not really a concern of this library how you expose the API.
