### ISSUE TITLE
[Server Sent Event] Streaming client is nil when connecting to subgraph

### ISSUE THREAD

**Issue by qiangfoo** [wundergraph/graphql-go-tools#428]
I'm trying to use subscriptions with SSE.

I use `NewFederationEngineConfigFactory` to generate the engine config. I notice that the `StreamingClient` is not initialized in this method. https://github.com/wundergraph/graphql-go-tools/blob/master/pkg/graphql/engine_config_v2.go#L91-L94

So when the engine tries to make a subscription request to subgraphs, it errors out at https://github.com/wundergraph/graphql-go-tools/blob/master/pkg/engine/datasource/graphql_datasource/graphql_subscription_client.go#L106-L108

Is there a way to pass the streaming client to the engine? or is this a bug?

**Comment by jensneuse** [comment]
This code needs to be updated. Please open a PR if you'd like to contribute. We (WunderGraph) don't use the graphql package. @pvormste or @buraksezer might be interested in fixing this?

**Comment by pvormste** [comment]
Hey @qiangfoo and @jensneuse,
we will fix this in the next weeks - it's already in our backlog!
