### ISSUE TITLE
[Feature Request] Support POST method in SSE requests

### ISSUE THREAD

**Issue by qiangfoo** [wundergraph/graphql-go-tools#429]
The SSE connection is hardcoded to use `GET` method (https://github.com/wundergraph/graphql-go-tools/blob/master/pkg/engine/datasource/graphql_datasource/graphql_sse_handler.go#L188). 

But for my use case, the graphql server only takes `POST` requests. I believe this is a very common practice in graphql servers. Can we make the http method configurable?

**Comment by jensneuse** [comment]
We don't have a use case for this, but you can open a PR if you're interested.

**Comment by spetrunin** [comment]
fixed by https://github.com/wundergraph/graphql-go-tools/pull/449
