### ISSUE TITLE
Federation - Optional variables in subqueries

### ISSUE THREAD

**Issue by argoyle** [wundergraph/graphql-go-tools#435]
I've stumbled upon something which I'm quite sure works in the Apollo Gateway.

Simplified schemas which produces the error below.

User service:
```graphql
type User @key(fields: "id") {
  id: ID!
  name: String!
}

type Query @extends {
  me: User!
}
```

Employee service:
```graphql
type User @extends @key(fields: "id") {
  id: ID! @external
  employment(companyId: ID!): Employee!
}

type Employee @key(fields: "id") {
  id: ID!
}
```

Time service:
```graphql
directive @goField(
  forceResolver: Boolean
  name: String
) on INPUT_FIELD_DEFINITION | FIELD_DEFINITION

scalar LocalTime

type Employee @extends @key(fields: "id") {
  id: ID! @external
  times(date: LocalTime): [TimeEntry]! @goField(forceResolver: true)
}

type TimeEntry {
  id: ID!
  employee: Employee!
  start: LocalTime!
  end: LocalTime
}
```

Query:
```graphql
query Times($companyId: ID!, $date: LocalTime) {
  me {
    employment(companyId: $companyId) {
      id
      times(date: $date) {
        id
        employee {
          id
        }
        start
        end
      }
    }
  }
}
```

Variables:
```json
{"companyId":"abc123"}
```

The result is my federation gateway saying `Get "": unsupported protocol scheme ""` in `engine.Execute` and returning a 500-error.

It has to do with variables and the fact that `date` is optional. If I provide a value for `date` the query works fine.

I'll try to create a failing test in a PR but my tries so far has failed. 🙈

I have a small repository which reproduces the error at least: https://github.com/argoyle/subgraph-error-repro

**Comment by argoyle** [comment]
Happy to make a try at least.

**Comment by argoyle** [comment]
Hmmm, I get a feeling that the problem is earlier than the resolve-step. My test still pass when changing the data-variable to null instead of a valid value.

**Comment by argoyle** [comment]
Debugging more shows that it fails to render the InputTemplate for the time-service query. The InputTemplate for the date context variable has `SetTemplateOutputToNullOnVariableNull` set to true even if the variable is optional. Not sure why my test doesn't show the same behaviour. I'll investigate more.

**Comment by argoyle** [comment]
Aaah, I had not set `SetTemplateOutputToNullOnVariableNull` on the InputTemplate in the test of course.

**Comment by argoyle** [comment]
I thought it might have to do with me using a custom scalar as my variable-type which seems to make the JSON schema for the validator be just `{}` so I changed it to a regular `String` which set the JSON schema to `{"type":["string","null"]}` but that didn't make a difference either.

**Comment by argoyle** [comment]
`SetTemplateOutputToNullOnVariableNull` is set from the fetch configuration which seems to be set to true for all federation batch-fetches, correct? Maybe we need to validate the variable if it's null and only set template output to null if invalid?

**Comment by jensneuse** [comment]
Thank you for all the work you've done. I have a little backlog but will look at this asap.

**Comment by argoyle** [comment]
@jensneuse The same seems to be true when passing header values to federated services (using `WithAdditionalHttpHeaders` and
```
Header: map[string][]string{
	"sentry-trace": {`{{.request.headers.sentry-trace}}`},
	"baggage":      {`{{.request.headers.baggage}}`},
},
```
in the datasource fetch config).

If a sentry-trace or baggage is not present in the client request the whole request fails with the same error (`Get "": unsupported protocol scheme ""`). Passing an empty string or a real value works as expected.

**Comment by spetrunin** [comment]
@argoyle both issues should be fixed - it was a regression
Could you check with latest master?

**Comment by argoyle** [comment]
🎉  Seems to work perfectly now. Thanks a lot @spetrunin and @jensneuse!
