### ISSUE TITLE
[Question] Diff two ASTs/schemas

### ISSUE THREAD

**Issue by argoyle** [wundergraph/graphql-go-tools#444]
Just a question, has anyone implemented a diff of two ASTs or schemas? For example a diff between the current version and a new version of a schema?

**Comment by jensneuse** [comment]
I'd say you can use any tool to print the schemas, sort them lexicographically, and then use existing diff tools. That should do.

**Comment by argoyle** [comment]
Hmmm, good point! Thanks!
