### ISSUE TITLE
Extending an Interface-Type fails

### ISSUE THREAD

**Issue by roderm** [wundergraph/graphql-go-tools#458]
If a type which implements an interface is extended, the it won't resolve and additionally the key is cleared.
I copied the federation example and modified it [here](https://github.com/roderm/federation-example), only the accounts-service has been modified:
```gql
extend type Query {
  me: User
  self: Identity
}

interface Identity {
  id: ID!
}

type User implements Identity @key(fields: "id") {
  id: ID!
  username: String!
}
```
The query for "me" which returns the User shows the correct result:
```gql
query {
  me {
    ... on User {
      id
      username
      reviews {
        body
      }
    }
  }
}
```
Result: 
```json
{
  "data": {
    "me": {
      "id": "1234",
      "username": "Me",
      "reviews": [
        {
          "body": "A highly effective form of birth control."
        },
        {
          "body": "Fedoras are one of the most fashionable hats around and can look great with a variety of outfits."
        }
      ]
    }
  }
}
```

But the Query for "self" which returns the interface fails:
```gql
query {
  self {
    id
    ... on User {
      uid: id
      username
      reviews {
        body
      }
    }
  }
}
```
Result: 
```json
{
  "data": {
    "self": {
      "uid": "1234",
      "username": "Me"
    }
  }
}
```
* the `id` is not set
* reviews aren't set, not even an empty array

In the logs from the `_entities` are correctly queried.
```
GraphQL Request {
  query($representations: [_Any!]!){_entities(representations: $representations){... on User {reviews {body}}}}
  var representations = [
    {
      "__typename": "User",
      "id": "1234"
    }
  ]
  resp: {
    "data": {
      "_entities": [
        {
          "reviews": [
            {
              "body": "A highly effective form of birth control."
            },
            {
              "body": "Fedoras are one of the most fashionable hats around and can look great with a variety of outfits."
            }
          ]
        }
      ]
    }
  }
}
```

**Comment by jensneuse** [comment]
Are you able to create a test for the GraphQL datasource with this use case? E.g. by extending the existing federation planning tests. I can take it from there I'd you don't know how to implement a fix.

**Comment by roderm** [comment]
@jensneuse I created a branch here: [https://github.com/roderm/graphql-go-tools/commits/issue-458](https://github.com/roderm/graphql-go-tools/commits/issue-458)
Where I copied the [federation-testcase](https://github.com/wundergraph/graphql-go-tools/blob/107c8e1f4a3384c19448430f9f5bb67db10a2b99/pkg/engine/datasource/graphql_datasource/graphql_datasource_test.go#L3557), extended the `federationTestSchema` and used the "self"-query.

Is this in the correct place? If you can point me to the right direction, I may can fix it.

**Comment by jensneuse** [comment]
Let me have a look

**Comment by Aenimus** [comment]
@roderm Hello!
[This PR](https://github.com/wundergraph/graphql-go-tools/pull/477) addresses the issue you've described. The PR is based on [another PR from almost a year ago](https://github.com/wundergraph/graphql-go-tools/pull/334/files).

I need to add a few more tests to make sure it's all robust, but I'll ping again once it's in master.

**Comment by Aenimus** [comment]
@roderm The PR has been merged.

Note that it's not a perfect solution. There are still issues, but examples like the above do now work.

The remaining issues are difficult to solve in the current state. The handling of abstract types and the like needs to be refactored.
