### ISSUE TITLE
graphql.Request.SetHeader doesn't work

### ISSUE THREAD

**Issue by daniil-kzn** [wundergraph/graphql-go-tools#459]
I set a new header to the graphql.Request but there is no the header in a subgraph service.
```
var gqlRequest graphql.Request
gqlRequest.SetHeader(http.Header{"Some-Header": []string{"some value"}})
```
[https://github.com/wundergraph/graphql-go-tools/blob/master/examples/federation/gateway/http/http.go#L21](https://github.com/wundergraph/graphql-go-tools/blob/master/examples/federation/gateway/http/http.go#L21)

Maybe there is an another way to sent a custom header to subgraph service.

**Comment by roderm** [comment]
You could add a `http.RoundTripper` to the [httpClient passed into DataSourcePoller](https://github.com/wundergraph/graphql-go-tools/blob/master/examples/federation/gateway/main.go#L50)
```go
type AddHeaderTransport struct {
	T      http.RoundTripper
}

func (t *AddHeaderTransport) RoundTrip(req *http.Request) (*http.Response, error) {
	req.Header.Add("Some-Header", "some value")
	return t.T.RoundTrip(req)
}
```
Creating the client:
```go
httpClient := http.DefaultClient
httpClient.Transport = &AddHeaderTransport{T: http.DefaultTransport}

datasourceWatcher := NewDatasourcePoller(httpClient, DatasourcePollerConfig{
	Services: []ServiceConfig{
		{Name: "accounts", URL: "http://localhost:4001/query"},
		{Name: "products", URL: "http://localhost:4002/query", WS: "ws://localhost:4002/query"},
		{Name: "reviews", URL: "http://localhost:4003/query"},
	},
	PollingInterval: 30 * time.Second,
})
```

**Comment by daniil-kzn** [comment]
It works but I explained my case not so clear.
The gateway receives some header from a frontend.
How can I pass the header to a subgraph?

**Comment by jensneuse** [comment]
You can pass client request headers like this to a subgraph:
https://github.com/wundergraph/graphql-go-tools/blob/607a7ec39dbf195cfe1ccf8b8c1f837f4670bbb0/pkg/engine/datasource/graphql_datasource/graphql_datasource_test.go#L180

**Comment by daniil-kzn** [comment]
c
https://github.com/wundergraph/graphql-go-tools/blob/607a7ec39dbf195cfe1ccf8b8c1f837f4670bbb0/examples/federation/gateway/http/http.go#L18

**Comment by mcondie** [comment]
@daniil-kzn You need to add the header passthrough in the configuration of the datasource. In the case of the example code: https://github.com/wundergraph/graphql-go-tools/blob/607a7ec39dbf195cfe1ccf8b8c1f837f4670bbb0/examples/federation/gateway/datasource_poller.go#L158

Add something like this: `Method: http.MethodPost,
				Header: http.Header{
					"Cookie": []string{"{{ .request.headers.Cookie }}"},
				},
`

**Comment by daniil-kzn** [comment]
it works! thanks a lot
