### ISSUE TITLE
does this project support apollo federation v2.0 ?

### ISSUE THREAD

**Issue by it512** [wundergraph/graphql-go-tools#462]
does this project support apollo federation v2.0 ?

**Comment by jensneuse** [comment]
Not yet, but some people are already looking at implementing it. Are you interested in helping?

**Comment by it512** [comment]
complete support 1.0 now ? 
I am try it 。

**Comment by codebdy** [comment]
Are you making progress?

**Comment by Aenimus** [comment]
@codebdy Watch this space!
https://wundergraph.com/blog/apollo_federation_v2_oss_coming
