### ISSUE TITLE
New Use Case: Chaos Proxy

### ISSUE THREAD

**Issue by flexzuu** [wundergraph/graphql-go-tools#49]
In the vains of New Relics [article](https://blog.newrelic.com/engineering/graphql-chaos-engineering/?utm_campaign=brn+awr++FY19Q4&utm_medium=OS&utm_source=TWIT) about chaos testing with graphql we had the idea to use the proxy to add this feature to any graphql api. 
Current ideas:

`@chaos` directive on field or type level to replace original response with error message

`@delay` directive on field or type level to slow down the whole response as soon as a field/type with this directive is used in the query

This is a placeholder issue and needs to be filled with more info!

**Comment by jensneuse** [comment]
I'd rather use something more descriptive like:

```graphql
"""
injectError will inject an error at the given error rate when a client requests the field
this is useful e.g. for chaos testing clients/consumers
"""
directive @injectError(
    errorRate: Float!
    errorMessage: String!
) on FIELD
```

```graphql

enum TimeUnit {
    Milliseconds
    Seconds
}

"""
injectDelay will artificially inject a delay whenever the annotated type is requested
"""
directive @injectDelay(
    delay: Integer!
    unit: TimeUnit!
) on TYPE
```

What do you think @mvid ?

**Comment by mvid** [comment]
I would say something like `@injectErrorChance` or `@injectedErrorPercent` or something so that it is clear that an error won't occur every time.

For the delay, I don't think a TimeUnit is required. Standardizing on seconds or milliseconds is probably simpler. `@injectDelaySeconds` or `@injectDelayMilliseconds`

Otherwise makes sense to me.

**Comment by jensneuse** [comment]
I think "injectedErrorPercent" is a good idea.

"@injectDelaySeconds" and "@injectDelayMilliseconds" look simple and concise to me.

**Comment by flexzuu** [comment]
Nope looks great
