### ISSUE TITLE
Arguments on interface fields aren't passed to service

### ISSUE THREAD

**Issue by roderm** [wundergraph/graphql-go-tools#495]
If an interface has a field with arguments, a request to the interface "directly" always gets `nil` arguments. If queried via an inline fragment the parameters are passed to the subgraph.

example Schema:
```graphql
interface User {
	id: ID!
	email: String
	roles(tenant: String): [String]
}

type BaseUser implements User {
	id: ID!
	email: String
	roles(tenant: String): [String]
}
type Query {
	user: User
}
```

Working example inline fragment:
```graphql
query UserRoles($tenant: String){
	user {
		... on BaseUser {
			roles(tenant: $tenant)
		}
	}
}
```
The `tenant`-string is correctly passed to the resolver.

**not** working example:
```graphql
query UserRoles($tenant: String){
	user {		
		roles(tenant: $tenant)
	}
}
```
The tenant-string is not passed and will always be `nil` or `""`.

### Tests
Branch: https://github.com/roderm/graphql-go-tools/tree/roderm/abstract-field-argument

The problem seems to be in the [execution engine v2](https://github.com/roderm/graphql-go-tools/commit/3639fc39fbbaf0317a9e467e252a1417b3791b48#diff-318fda8fb3d273cbbbde93201ad6e54bf4774bd7f4522b19f323e884f2c7e82e):
* `query interface-field with argument and type specification` mimiks the inline fragment and works properly
* `query interface-field with argument` queries the fields on the interface and fails on `graphql_datasource.Factory`/`expectedBody`

I tried creating test-cases in [graphql-datasource](https://github.com/roderm/graphql-go-tools/commit/3639fc39fbbaf0317a9e467e252a1417b3791b48#diff-a9a261cb37ea0ad0b90f7e0fefa3e29adf43b0cd23ca1c3f7b528e34fba83834), which work as expected.

**Comment by roderm** [comment]
As I can see now, a lot has changed and the test-cases work now. Unfortunately, it still doesn't work as an application. I tracked a few things down:
* The [`EnterField`](https://github.com/wundergraph/graphql-go-tools/blob/0c3d635b9c18f6640a06e9873b47d75f9ba9371f/pkg/engine/plan/plan.go#L1785) in the plan always receives  `fieldConfig == nil`. The [`ForTypeField`](https://github.com/wundergraph/graphql-go-tools/blob/0c3d635b9c18f6640a06e9873b47d75f9ba9371f/pkg/engine/plan/plan.go#L102) loops the given fields which don't include Interface-Types.
* The fields are loaded in the https://github.com/wundergraph/graphql-go-tools/blob/0c3d635b9c18f6640a06e9873b47d75f9ba9371f/pkg/engine/plan/required_field_extractor.go .

Can I just add the Interface-Type to [required_field_extractor.go](https://github.com/wundergraph/graphql-go-tools/blob/0c3d635b9c18f6640a06e9873b47d75f9ba9371f/pkg/engine/plan/required_field_extractor.go)?
If yes, can there be the same case on unions?

**Comment by devsergiy** [comment]
Hi @roderm 

please try to use an updated federation example https://github.com/wundergraph/graphql-go-tools/tree/master/examples/federation
