### ISSUE TITLE
Something is wrong with subgraph validation

### ISSUE THREAD

**Issue by ikawaha** [wundergraph/graphql-go-tools#498]
Thanks for the great library.

I am using the library and report that I have some concerns about the behaviour of the subgraph validation. Draft fixes are also included. I hope this is helpful.

# TL;DR;

There appear to be two problems with [validateSubgraph()](https://github.com/wundergraph/graphql-go-tools/blob/1bb9a1fc44364bb3d770bcc05a2322d49a00e171/pkg/federation/sdlmerge/sdlmerge.go#L72-L90):

1. If a field type is the non-null type, it will be ignored by the validation.
2. Extend field type definitons are ignored by validation.

# Preliminaries

The function [func sdlmerge.MergeSDLs(SDLs . . string) (string, error)](https://github.com/wundergraph/graphql-go-tools/blob/1bb9a1fc44364bb3d770bcc05a2322d49a00e171/pkg/federation/sdlmerge/sdlmerge.go#L39-L70) provides a function [function func validateSubgraphs(subgraphs []string) error](https://github.com/wundergraph/graphql-go-tools/blob/1bb9a1fc44364bb3d770bcc05a2322d49a00e171/pkg/federation/sdlmerge/sdlmerge.go#L72-L90) to validate given subgraphs.

In `validateSubgraphs()`, each subgraph is merged with the base schema and validated.

Validation checks that the types defined in the subgraphs (held in definedTypeNameHashes) correspond to the referenced types (held in referencedTypeNames).

https://github.com/wundergraph/graphql-go-tools/blob/1bb9a1fc44364bb3d770bcc05a2322d49a00e171/pkg/astvalidation/rule_known_type_names.go#L44-L52

# Problems

There seem to be two problems with `validateSubgraph()`:

1. If a field type is specified as non-null (e.g. 'User!' ), it is not registered in definedTypeNameHashes.
2. Extended field types are not registered in definedTypeNameHashes.

The following subgraphs are discussed below. This subgraph is a valid subgraph.

````graphql 
type Review {
    body: String!
    author: User @provides(fields: "username")
    product: Product
}

type User @key(fields: "id") {
    id: ID!
    username: String!
    reviews: [Review] 
}

extend type Product @key(fields: "upc") {
    id: ID! @external
    reviews: [Review]
}
````

## 1. If a field type is the non-null type, it will be ignored by the validation.

**Demonstration code:** => https://github.com/ikawaha/graphql-go-tools/pull/1/commits/91497377b8051238814530f0cb9dc02df085032a

The expected result of this sub-graph would be a validation failure because it does not have a 'Product' definition, but it does not.

```graphql
type Review {
    body: String!
    author: User! @provides(fields: "username")
    product: Product!
}

type User @key(fields: "id") {
    id: ID! @external
    username: String! @external
    reviews: [Review]
}

#extend type Product @key(fields: "upc") {  // ← comment out Product definition
#    id: ID! @external
#    reviews: [Review]
#}
```

The expected result of this sub-graph would be a validation failure because it does not have a 'Product' definition, but it does not.

```graphql
type Review {
    body: String!
    author: User! @provides(fields: "username")
    product: Product!
}

#type User @key(fields: "id") {  // ← comment out User definition
#    id: ID! @external
#    username: String! @external
#    reviews: [Review]
#}

extend type Product @key(fields: "upc") {
    upc: String! @external
    reviews: [Review]
}
```

Also, the following will not cause errors in validation.

```graphql
type Review {
    body: String!
    author: User!
    product: Product!
}
```

This is because non-null field definitions are created by the combination of TypeKindNonNull and TypeKindNamed field definitions. Non-Null field definitions are represented by TypeKindNonNull field definitions. The definitions of TypeKindNonNull do not contain a type name. To know the type name it is necessary to refer to the ofType field.

```Go
func (p *Parser) ParseType() (ref int) {

	first := p.peek()

	if first == keyword.IDENT {
		tok := p.read()
		ref = p.document.AddNamedTypeWithPosition(tok.Literal, tok.TextPosition)
	} else if first == keyword.LBRACK {

		openList := p.read()
		ofType := p.ParseType()
		closeList := p.mustRead(keyword.RBRACK)

		ref = p.document.AddListTypeWithPosition(ofType, openList.TextPosition, closeList.TextPosition)
	} else {
		p.errUnexpectedToken(p.read(), keyword.IDENT, keyword.LBRACK)
		return
	}

	next := p.peek()
	if next == keyword.BANG {
		bangPosition := p.read().TextPosition
		if p.peek() == keyword.BANG {
			p.errUnexpectedToken(p.read())
			return
		}

		ref = p.document.AddNonNullTypeWithBangPosition(ref, bangPosition) // ← ★ if non-null, store original ref in ofType and return ref of TypeKindNonNull
	}

	return
}
```

By the way, the knownTypeNamesVisitor collects information about the type a field has a reference to.

```Go
func (u *knownTypeNamesVisitor) EnterFieldDefinition(ref int) {
	referencedTypeRef := u.definition.FieldDefinitions[ref].Type
	referencedTypeName := u.definition.TypeNameBytes(referencedTypeRef) // name is empty if ref type is TypeKindNonNull
	u.saveReferencedTypeName(referencedTypeName)
}
```

In this case, if a non-null field ref is passed to the above function, the type name cannot be retrieved. Therefore, it will not be recorded as a referenced type and will not be checked if there is no reference to it.

````Go
func (u *knownTypeNamesVisitor) LeaveDocument(_, _ *ast.Document) {
	for referencedTypeNameHash, referencedTypeName := range u.referencedTypeNames { // ← non-null types are not in here
		if !u.definedTypeNameHashs[referencedTypeNameHash] {
			u.Report.AddExternalError(operationreport.ErrTypeUndefined(referencedTypeName))
			continue
		}
	}
}
````

## 2. Extend field type definitons are ignored by validation.

The following is a complete subgraph. However, validation will point out that 'Product' is missing.

```graphql
type Review {
    body: String!
    author: User @provides(fields: "username")
    product: Product
}

type User @key(fields: "id") {
    id: ID!
    username: String!
    reviews: [Review]
}

extend type Product @key(fields: "upc") {
    @external
    reviews: [Review]
}
```

The validation specifies astvalidation.KnownTypeNames() to the visitor to collect the types in use.

```Go
	validator := astvalidation.NewDefinitionValidator(
		astvalidation.PopulatedTypeBodies(), astvalidation.KnownTypeNames(),
	)
```	

I think it is necessary to add walker.RegisterEnterObjectTypeExtensionVisitor here.

```Go
func KnownTypeNames() Rule {
	return func(walker *astvisitor.Walker) {
		visitor := &knownTypeNamesVisitor{
			Walker: walker,
		}

		walker.RegisterDocumentVisitor(visitor)
		walker.RegisterEnterRootOperationTypeDefinitionVisitor(visitor)
		walker.RegisterEnterFieldDefinitionVisitor(visitor)
		walker.RegisterEnterUnionMemberTypeVisitor(visitor)
		walker.RegisterEnterInputValueDefinitionVisitor(visitor)
		walker.RegisterEnterObjectTypeDefinitionVisitor(visitor)
		walker.RegisterEnterObjectTypeExtensionVisitor(visitor)  // ← ★
		walker.RegisterEnterInterfaceTypeDefinitionVisitor(visitor)
		walker.RegisterEnterScalarTypeDefinitionVisitor(visitor)
		walker.RegisterEnterUnionTypeDefinitionVisitor(visitor)
		walker.RegisterEnterInputObjectTypeDefinitionVisitor(visitor)
		walker.RegisterEnterEnumTypeDefinitionVisitor(visitor)
	}
}
```

**Comment by jensneuse** [comment]
hey, I'd love to talk to you! It would be nice if you could join our discord and we'll have a chat: https://wundergraph.com/discord

**Comment by ikawaha** [comment]
I would like to submit a pull-request if the draft fix is correct.
https://github.com/ikawaha/graphql-go-tools/pull/1

**Comment by spetrunin** [comment]
@ikawaha thanks a lot for your contribution

fix is included here https://github.com/wundergraph/graphql-go-tools/releases/tag/v1.61.4
