### ISSUE TITLE
Duplicate Directive

### ISSUE THREAD

**Issue by PBholewasi** [wundergraph/graphql-go-tools#517]
While having same directive in multiple schema, the merged schema have duplicate directive definition.

**Comment by jensneuse** [comment]
This is quite possible a problem. That you for reporting. We currently don't need this functionality as we're using graphql-js for this sort of task. You'd like to open a PR with a proposed fix?

**Comment by PBholewasi** [comment]
Yes @jensneuse can we have this fix so that we can have unique directives in the merged schema.

**Comment by slavik-pastushenko** [comment]
Hello! Any solutions yet?
