### ISSUE TITLE
Federation server doesn't start if super graph fails to build on startup

### ISSUE THREAD

**Issue by soonick** [wundergraph/graphql-go-tools#523]
Hello!

I created a [PR as a proposal](https://github.com/wundergraph/graphql-go-tools/pull/521) for increasing the availability of the federated graph in some edge cases. It still needs some polishing, but I included it to start the conversation.

Currently, when a backend service is down, it can prevent the gateway from starting if the service provides some definitions required by other services. This PR proposes adding an optional attribute to the service configuration that can be used to execute some fallback behavior if we fail to communicate with some backend service during startup. In the PR I just read the graph from the filesystem, but my intention is to keep a registry of schemas where I can pull the latest stable version.

Before my change, running examples/federation without the accounts service would prevent the gateway from creating a valid supergraph. After my PR, the Gateway can start correctly.

**Comment by jensneuse** [comment]
Thank you for the contribution!
