### ISSUE TITLE
When using Federation and Fragment, panic occurs when typename is specified.

### ISSUE THREAD

**Issue by Mistat** [wundergraph/graphql-go-tools#525]
This occurs when using Federation and Fragment with the __typename problem.

Example

SubGraphA
```
type Group {
  :
}
type Query {
  group(id: ID!) Group
}
```

SubGraphB
```
type Employee {
  :
}
type Query {
  employee(id: ID!) Group
}
```

Query
```
{
  group(id: "xxx") {
     :
  }
  employee(id: "xxx") {
     ... EmployeeItem
    __typename // <-- This would be an error
  }
}

fragment EmployeeItem on Employee {
 :
}
```

Then,  Panic occurs because this fieldConfig is nil in the case 

https://github.com/wundergraph/graphql-go-tools/blob/master/pkg/engine/datasource/graphql_datasource/graphql_datasource.go#L680-L683

**Comment by Mistat** [comment]
I have tried workaround fix
https://github.com/wundergraph/graphql-go-tools/pull/526

**Comment by Aenimus** [comment]
This has been fixed.
https://github.com/wundergraph/graphql-go-tools/commit/b0e183c3230a72ccac153a776f8fbff671edfb38
