### ISSUE TITLE
Transparent Pass-Through of Scalar Types from Subgraphs

### ISSUE THREAD

**Issue by steve-gray** [wundergraph/graphql-go-tools#530]
Where a subgraph defines a scalar, this package should pass through the value verbatim. At the moment when federating a type that is a custom scaler, there's an error about "invalid value type" as it tries to fall back to string handling for all Scalars. There's no reason to reason about/introspect about the internals of these types - they can just be passed through verbatim to the client (or up to the target in the case of an input type field).

There appears to be some provision for this in the framework with RenameType operations in some areas, but this is either not working for this purpose, or poorly documented otherwise.

**Comment by devsergiy** [comment]
fixed by https://github.com/wundergraph/graphql-go-tools/pull/613
