### ISSUE TITLE
Error in query building

### ISSUE THREAD

**Issue by luca147** [wundergraph/graphql-go-tools#572]
I think something is wrong, why the lib remove the operation name from the query?

Original request:

```
query MyHeroes($heroNames: [String!]!){
						heroes(names: $heroNames)
					}
```

And the lib send this to graphql sub-graphs:

`{"query":"query($heroNames: [String!]!){heroes(names: $heroNames)}","variables":{"heroNames":["Luke Skywalker","R2-D2"]}}`

I get the error: **Anonymous operations are not allowed** so i can not use it :/

**Comment by luca147** [comment]
@jensneuse can help me?

**Comment by devsergiy** [comment]
Hi @luca147 

We do not know anything about your use case and what exactly you are using from this library

If such an issue still exits please provide a complete reproducible example
