### ISSUE TITLE
Is it ready for production yet ?

### ISSUE THREAD

**Issue by loockeeer** [wundergraph/graphql-go-tools#576]
Hi ! I just wanted to know if that project was "production ready" already, according to the maintainers.
I am asking for me and my team since we want to go full graphql & microservices without the crazy prices of Apollo.

Thank you in advance !

**Comment by Aenimus** [comment]
@loockeeer graphql-go-tools has been ready for production for several years. It is used in productions by countless companies today. :)

If you have a specific question or concern, you can contact us on Discord: https://discord.gg/CHU4sUJhQ9
