### ISSUE TITLE
Custom scalar cannot be nullable and cannot resolve null.

### ISSUE THREAD

**Issue by LimhorngSok** [wundergraph/graphql-go-tools#618]
Hi
I ran into a problem where I define a custom scalar called `Uint` and I have a schema like this

Game{
  playerOneID: Uint
  playerTwoID:  Uint
  WinnerID: Uint
}

When I tried to query Game and the WinnerID is null it always return `unable to resolve`
As I checked the code in lib, I found that my `CustomNode.Nullable is false`.

Here is my customScalar

type UintResolver struct {
	Nullable bool
}

// UintResolver implements resolve.CustomResolve.
func (UintResolver) Resolve(data []byte) ([]byte, error) {
	return data, nil
}

// Create resolver map
var customResolveMap = map[string]resolve.CustomResolve{
	"Uint": &UintResolver{Nullable: true},
}

or is there a way to make this CustomNode.Nullable = true?

**Comment by BenjaminYong** [comment]
Did you ever find out how to do this @LimhorngSok ? Running into a similar issue with custom scalar is null, the entire object response becomes null with it:


```
query getScopes {
  getScopes {
    scope
    type
    jsonScopeArgs   # <-- JSON custom scalar (same resolver as yours)
    __typename
  }
}
```

```
{
  "data": {
    "getScopes": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ]
  }
}
```

If I dont return the custom scalar, things return fine. Otherwise, if the custom scalar is not null, it will also return fine
