### ISSUE TITLE
configurationVisitor.handleMissingPath: could not plan a field Mutation.__typename on a path mutation.__typename 

### ISSUE THREAD

**Issue by cs-clarence** [wundergraph/graphql-go-tools#623]
Mutations with `__typename` fails. I am using cosmo router but I posted it here because it looks like the underlying error is in graphql-go-tools
It seems that cosmo router doesn't support this kind of mutation:

```graphql
mutation M {  
  __typename # mutations with this causes the error
  CreateUser() {
    __typename
    # skip
  }
}
```

In playground:
![image](https://github.com/wundergraph/graphql-go-tools/assets/71768661/d0200884-71fe-44a7-86e8-c2895e8d46a8)

__typename on root query node works fine:
![image](https://github.com/wundergraph/graphql-go-tools/assets/71768661/98c16b67-a3dd-46c7-ac2b-bc0c564f76f3)

**Comment by vikstrous2** [comment]
I ran into the same issue with
```
query Q {
  __typename
}
```
