### ISSUE TITLE
JSON serialised header values don't work

### ISSUE THREAD

**Issue by gustavooferreira** [wundergraph/graphql-go-tools#631]
Hi,

First of all, thank you very much for this fantastic library.

When calling my subgraphs I need to pass a serialised JSON object in the headers.

I was able to inject the header into the engine and then use the templating on the data source configuration to make sure it was used on the outbound requests to the subgraphs.

The problem is however that, because of how the [InputTemplate](https://github.com/wundergraph/graphql-go-tools/blob/master/pkg/engine/resolve/inputtemplate.go#L30) is being generated, itself uses JSON to be constructed, so when one of the header values is a JSON serialised it messes up the entire structure.

As an example, for an incoming graphql request, the input template would look like this:
```json
{
  "method": "POST",
  "url": "http://localhost:8081",
  "header": {
    "Authorization": [
      "Bearer token"
    ],
    "my-header-object": [
      "{"groups":["group-1", "group-2"], "email": "my-email@google.com"}"    <---- This messes up the entire input template
    ]
  },
  "body": {
    "query": "{availableTags {color name}}"
  }
}
```

I was wondering if we should escape the values somehow because anything that includes quotes would mess up the input template.

And also, is there any particular reason we can't use a `beforeHook` of some sort that would get called with all the context including the request that was made to the gateway with the headers so that we could dynamically decide what headers we want to include in the subgraphs requests.

I have a use case where I only include a header in certain scenarios, regardless of whether the header exists in the incoming request to the gateway. Having a `beforeHook` of sorts would allow the developer to write code to control when to send what headers, similar to what Apollo Gateway does.

**Comment by jensneuse** [comment]
Sounds like you need to tweak the planner in your case to plan with a different kind of renderer.
