### ISSUE TITLE
Federation gateway incorrectly strips default values from operations

### ISSUE THREAD

**Issue by soonick** [wundergraph/graphql-go-tools#640]
I found an issue in the way federation gateway handles operations with default arguments. I created a branch that can be used to reproduce the issue: https://github.com/soonick/graphql-go-tools/tree/federation.bug

To reproduce, go to examples/federation and run `./start.sh`.

Curl the products service directly:

```
curl 'http://localhost:4002/query' -H 'Content-Type: application/json' --data-raw '{"variables":{"first": 4}, "query": "query($first: Int = 3) { topProducts(first: $first){ upc name } }"}'
```

The query runs as expected. If we try to run the query against the federation router we will get an error:

```
curl 'http://localhost:4000/query' -H 'Content-Type: application/json' --data-raw '{"variables":{"first": 4}, "query": "query($first: Int = 3) { topProducts(first: $first){ upc name } }"}'

{"errors":[{"message":"Variable \"$first\" of type \"Int\" used in position expecting type \"Int!\".","locations":[{"line":1,"column":39}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}}],"data":{"topProducts":null}}
```

This error comes from the products service because the federation gateway rewrites the query the following invalid query:

```
query($first: Int){topProducts(first: $first){upc name}}
```

Note how it has `$first: Int` instead of `$first: Int = 3`, which fails validation by most GQL parsers.

I've spent some hours trying to figure out where this happens, but haven't been able to find where / how the outgoing queries are generated. Any pointers would be appreciated

**Comment by soonick** [comment]
I think I found the root cause for this issue. Would appreciate if someone can take a look: https://github.com/wundergraph/graphql-go-tools/pull/642

**Comment by devsergiy** [comment]
Hi @soonick 

sorry for the late response, we were very busy with the v2 version of the engine

I'm afraid this is the bug in the gqlgen query validator, according to the [spec](https://spec.graphql.org/June2018/#sec-All-Variable-Usages-are-Allowed) in case the argument has a default value in the schema, you could use a nullable variable

And it is dangerous to make variables non-null unconditionally

**Comment by devsergiy** [comment]
Hi @soonick 

We have included part of your fix in this PR https://github.com/wundergraph/graphql-go-tools/pull/726 for v2 version

Thanks a lot for the contribution!
