### ISSUE TITLE
Searching through federation.

### ISSUE THREAD

**Issue by daniil-kzn** [wundergraph/graphql-go-tools#652]
There are two microservices with separated databases.

1. User microservice (user db)
```
type User {
    id:ID! 
    name: String!
}
```
2. Post microservice (post db)
```
extend type User @key(fields: "id") {
    id: ID!
    posts: [Post]
}
type Post {
    id:ID! 
    title: String!
}
```

How can I get all users where User.name="foo" and Post.title = "%some pattern%"?

**Comment by Aenimus** [comment]
Hi @daniil-kzn,

This is not a case that GraphQL supplies "out of the box". You would need to add support in your graphs and resolvers to achieve your desired result. Consultancy is not a service we are able to provide through a GitHub issue.

However, if you are interested in consultancy services, you can set up a call with our sales team using this link:
https://cal.com/stefan-avram-wundergraph/wundergraph-introduction

Thanks,

The WunderGraph Team
