### ISSUE TITLE
Switch Custom to generics

### ISSUE THREAD

**Issue by clayne11** [wundergraph/graphql-go-tools#731]
Now that Go supports generics, should we consider using them for the [Custom field](https://github.com/wundergraph/graphql-go-tools/blob/309f5bb2cf9e4a7bf5fdaef8cbcd2a5347ed9113/v2/pkg/engine/plan/datasource_configuration.go#L38)?

I've looked through the code a decent amount and this seems like a reasonable idea to improve typesafety / understandability / performance.

**Comment by jensneuse** [comment]
Good idea. You'd like to contribute an improvement?

**Comment by clayne11** [comment]
This is unfortunately not possible due to Go lacking slice covariance: https://blog.merovius.de/posts/2018-06-03-why-doesnt-go-have-variance-in/.
