### ISSUE TITLE
__typename field in _type query resolves to null

### ISSUE THREAD

**Issue by BenjaminYong** [wundergraph/graphql-go-tools#740]
Hi again @devsergiy,

I am trying out the [v1 federation example](https://github.com/wundergraph/graphql-go-tools/tree/master/examples/federation) and getting some unexpected behaviour around the `__type` query when returned with `__typename` field. I use this for schema and type introspection.

1. When I run a query without `__typename`, it returns as expected like this:
```
query type{
  __type(name: "User") {
    name
    fields{
      name
    }
  }
}
```

```
{
  "data": {
    "__type": {
      "name": "User",
      "fields": [
        {
          "name": "id"
        },
        {
          "name": "username"
        },
        {
          "name": "reviews"
        }
      ]
    }
  }
}
```

2. As soon as I return `__typename`, the object is resolved unexpectedly as null:

```
query type{
  __type(name: "User") {
    name
    __typename
    fields{
      name
    }
  }
}
```

```
{
  "data": {
    "__type": null
  }
}
```

3. Similarly, if I add `__typename` to just the `fields`object, that object unexpectedly becomes null instead:

```
query type{
  __type(name: "User") {
    name
    fields{
      name
      __typename
    }
  }
}
```

```
{
  "data": {
    "__type": {
      "name": "User",
      "fields": null
    }
  }
}
```

4. If I was to add `__typename` to the `me` query, it works fine as expected:
```
query me{
	me{
    id
    reviews{
      body
      __typename
    }
    __typename
  }
}
```

```
{
  "data": {
    "me": {
      "id": "1234",
      "reviews": [
        {
          "body": "A highly effective form of birth control.",
          "__typename": "Review"
        },
        {
          "body": "Fedoras are one of the most fashionable hats around and can look great with a variety of outfits.",
          "__typename": "Review"
        }
      ],
      "__typename": "User"
    }
  }
}
```

Your advice would be appreciated on how I can continue to use `__typename` in the `_type` query. It is used by our Apollo Client for caching purposes. Is this intended behaviour?

Thanks,
Ben

**Comment by BenjaminYong** [comment]
Another issue I just discovered with the Federation example `__type` query, is that the description subfield/s are resolved as `""` rather than `null` when compared with `__type` query called directly in the subgraph.

i.e.

Federation Gateway:
```
query type{
  __type(name: "User") {
    name
    description
    fields{
      name
      description
    }
  }
}
```

```
{
  "data": {
    "__type": {
      "name": "User",
      "description": "",
      "fields": [
        {
          "name": "id",
          "description": ""
        },
        {
          "name": "username",
          "description": ""
        },
        {
          "name": "reviews",
          "description": ""
        }
      ]
    }
  }
}
```


Compared to subgraph:
```
query type{
  __type(name: "User") {
    name
    description
    fields{
      name
      description
    }
  }
}
```

```
{
  "data": {
    "__type": {
      "name": "User",
      "description": null,
      "fields": [
        {
          "name": "id",
          "description": null
        },
        {
          "name": "username",
          "description": null
        }
      ]
    }
  }
}
```

**Comment by BenjaminYong** [comment]
Thanks for replying @Aenimus , do you have rough dates/timeline for when v2 will be ready?

**Comment by Aenimus** [comment]
@BenjaminYong V2 is already ready. However, if your question is regarding the porting of examples, there is no current time frame.
