### ISSUE TITLE
Finding resolver for Entity: type not found

### ISSUE THREAD

**Issue by niklod** [wundergraph/graphql-go-tools#745]
### What happened?
I’m trying to setup communication via GQL federation between two services.
`Service A` serves reviews and `service B` resolves review's author by ID.

Getting an error when trying to resolve `nil` extended entity `Author`
```
finding resolver for Entity "Author": type not found for Author
```

For some reason, federation trying to resolve a `nil` value `Author`

### What did you expect?
When I return `nil` `Author` (in service A), resolver `FindAuthorBySlug` (in service B) ignores it and doesn't try to resolve the `nil` value.

### Minimal graphql.schema and models to reproduce
GraphQL schema (Service A)
```graphql
extend type Query {
    reviews: ReviewsQuery
}

type ReviewsQuery {
    reviews: [Review!]
}

type Review {
    id: ID!
    author: Author @provides(fields: "slug")
}

extend type Author @key(fields: "slug"){
    slug: String! @external
}
```

GraphQL schema(Service B)
```graphql
type Author @key(fields: "slug"){
    slug: String!
    name: String
}
```

FindAuthorBySlug resolver (generated by gqlgen in Service B)
```go
func (r *entityResolver) FindAuthorBySlug(ctx context.Context, slug string) (*model.Author, error) {
	switch slug {
	case "author-a":
		return &model.Author{
			Slug: "author-a",
			Name: pointer.To("Author A"),
		}, nil
	case "author-b":
		return &model.Author{
			Slug: "author-b",
			Name: pointer.To("Author B"),
		}, nil
	default:
		return nil, nil
	}
}
```

Reviews resolver (generated by gqlgen in Service A)
```go
func (r *reviewsQueryResolver) Reviews(ctx context.Context, obj *models.ReviewsQuery) ([]models.Review, error) {
	return []models.Review{
		{
			ID: "review-a",
			Author: &models.Author{
				Slug: "author-a",
			},
		},
		{
			ID:     "review-c",
			Author: nil,
		},
		{
			ID: "review-b",
			Author: &models.Author{
				Slug: "author-b",
			},
		},
	}, nil
}
```

### versions
```
github.com/99designs/gqlgen v0.17.41
github.com/wundergraph/graphql-go-tools v1.52.1
```

**Comment by devsergiy** [comment]
Hi @niklod 

please try to use v2 and the execution package
v1 is no longer supported

the way to go is https://github.com/wundergraph/graphql-go-tools/tree/master/examples/federation
