### ISSUE TITLE
Empty response fetching from static data source

### ISSUE THREAD

**Issue by mattjohnsonpint** [wundergraph/graphql-go-tools#761]
I'm going through the tutorial, and while each piece is explained well, I can't get it to work end-to-end. 

Here's my attempt:

```go
package main

import (
	"bytes"
	"context"
	"fmt"

	"github.com/wundergraph/graphql-go-tools/v2/pkg/ast"
	"github.com/wundergraph/graphql-go-tools/v2/pkg/astparser"
	"github.com/wundergraph/graphql-go-tools/v2/pkg/asttransform"
	"github.com/wundergraph/graphql-go-tools/v2/pkg/engine/datasource/staticdatasource"
	"github.com/wundergraph/graphql-go-tools/v2/pkg/engine/plan"
	"github.com/wundergraph/graphql-go-tools/v2/pkg/engine/resolve"
	"github.com/wundergraph/graphql-go-tools/v2/pkg/operationreport"
)

func main() {

	staticDataSource, err := plan.NewDataSourceConfiguration(
		"StaticDataSource",
		&staticdatasource.Factory[staticdatasource.Configuration]{},
		&plan.DataSourceMetadata{
			RootNodes: []plan.TypeField{{
				TypeName:   "Query",
				FieldNames: []string{"hello"},
			}}},
		staticdatasource.Configuration{
			Data: `{"hello":"world"}`,
		},
	)
	if err != nil {
		panic(err)
	}

	config := plan.Configuration{
		DataSources: []plan.DataSource{staticDataSource},
		Fields: []plan.FieldConfiguration{{
			TypeName:  "Query",
			FieldName: "hello",
			Path:      []string{"hello"},
		}},
		IncludeInfo: true,
	}

	operationDocument := ast.NewSmallDocument()
	operationDocument.Input.ResetInputString("query MyQuery { hello }")

	schemaDocument := ast.NewSmallDocument()
	schemaDocument.Input.ResetInputString("type Query { hello: String }")

	report := &operationreport.Report{}
	operationName := "MyQuery"
	parser := astparser.NewParser()

	parser.Parse(operationDocument, report)
	if report.HasErrors() {
		panic(report.Error())
	}

	parser.Parse(schemaDocument, report)
	if report.HasErrors() {
		panic(report.Error())
	}

	asttransform.MergeDefinitionWithBaseSchema(schemaDocument)

	planner, err := plan.NewPlanner(config)
	if err != nil {
		panic(err)
	}

	executionPlan := planner.Plan(operationDocument, schemaDocument, operationName, report)
	if report.HasErrors() {
		panic(report.Error())
	}

	resolver := resolve.New(context.Background(),
		resolve.ResolverOptions{
			MaxConcurrency: 1024,
		})

	ctx := resolve.NewContext(context.Background())

	switch p := executionPlan.(type) {
	case *plan.SynchronousResponsePlan:
		out := &bytes.Buffer{}
		err := resolver.ResolveGraphQLResponse(ctx, p.Response, nil, out)
		if err != nil {
			panic(err)
		}
		fmt.Println(out.String())
	}
}
```

I don't get any panic, but the resulting output gives:

```json
{"errors":[{"message":"Failed to fetch from Subgraph 'StaticDataSource' at path 'query', empty response."}],"data":null}
```

What am I missing?  Thanks.

**Comment by jensneuse** [comment]
I think this is missing in your execution plan:
https://github.com/wundergraph/graphql-go-tools/blob/95ebc94f0714ff8fba1f50d7357e94eca9d10753/v2/pkg/engine/datasource/graphql_datasource/graphql_datasource_federation_entity_interfaces_test.go#L34

**Comment by mattjohnsonpint** [comment]
Sorry, I don't understand.  I'm just using the built-in static data source, as shown in the tutorial.  `PostProcessing` appears to be an option on `FetchConfiguration`, which isn't exposed to me as far as I can tell.

Or are you suggesting it should be added here:
https://github.com/wundergraph/graphql-go-tools/blob/95ebc94f0714ff8fba1f50d7357e94eca9d10753/v2/pkg/engine/datasource/staticdatasource/static_datasource.go#L53-L58

**Comment by mattjohnsonpint** [comment]
FWIW, I tried creating my own data source based on the static data source, so I could set `PostProcesing`.

```go
type MyFactory struct {
	staticdatasource.Factory[staticdatasource.Configuration]
}

type MyPlanner struct {
	config staticdatasource.Configuration
	staticdatasource.Planner[staticdatasource.Configuration]
}

func (f *MyFactory) Planner(logger abstractlogger.Logger) plan.DataSourcePlanner[staticdatasource.Configuration] {
	return &MyPlanner{}
}

func (p *MyPlanner) ConfigureFetch() resolve.FetchConfiguration {
	return resolve.FetchConfiguration{
		Input:      p.config.Data,
		DataSource: staticdatasource.Source{},
		PostProcessing: resolve.PostProcessingConfiguration{
			SelectResponseDataPath:   []string{"data"},
			SelectResponseErrorsPath: []string{"errors"},
		},
	}
}
```

It had no affect.  The result is the same.

**Comment by mattjohnsonpint** [comment]
Still haven't figured out how to fix it correctly, but through debugging I found that by the time it gets to loading data from the data source here:

https://github.com/wundergraph/graphql-go-tools/blob/master/v2/pkg/engine/datasource/staticdatasource/static_datasource.go#L68-L71

The `input` slice is empty.  If I manually set it to the original data (ie. `input = []byte(`{"hello":"world"}`)`) then the rest of it works and I get the correct output.

I think there's a bug somewhere, but I've not figured out whether its in my code or in the library.

**Comment by mattjohnsonpint** [comment]
I stumbled upon a test that uses the static data source, [`BenchmarkExecutionEngineV2`](https://github.com/wundergraph/graphql-go-tools/blob/95ebc94f0714ff8fba1f50d7357e94eca9d10753/v2/pkg/graphql/execution_engine_v2_test.go#L1605-L1687). 
 It's currently failing, but I was able to get it to pass with two small changes:

https://github.com/wundergraph/graphql-go-tools/blob/95ebc94f0714ff8fba1f50d7357e94eca9d10753/v2/pkg/graphql/execution_engine_v2_test.go#L1626-L1628

change to:

```go
staticdatasource.Configuration{
	Data: `{"hello": "world"}`,
},
```

and then:

https://github.com/wundergraph/graphql-go-tools/blob/95ebc94f0714ff8fba1f50d7357e94eca9d10753/v2/pkg/graphql/execution_engine_v2_test.go#L1640

Set `DisableDefaultMapping` to `false` (or remove line)

The test then passes.

From there, I was able to adapt that to an end-to-end version of what I was originally trying to do:

```go
package main

import (
	"context"

	"github.com/jensneuse/abstractlogger"
	"github.com/wundergraph/graphql-go-tools/v2/pkg/engine/datasource/staticdatasource"
	"github.com/wundergraph/graphql-go-tools/v2/pkg/engine/plan"
	"github.com/wundergraph/graphql-go-tools/v2/pkg/graphql"
)

func main() {
	schema, err := graphql.NewSchemaFromString(`type Query { hello: String}`)
	if err != nil {
		panic(err)
	}

	dsCfg, err := plan.NewDataSourceConfiguration(
		"MyStaticDataSource",
		&staticdatasource.Factory[staticdatasource.Configuration]{},
		&plan.DataSourceMetadata{
			RootNodes: []plan.TypeField{
				{
					TypeName:   "Query",
					FieldNames: []string{"hello"},
				},
			},
		},
		staticdatasource.Configuration{
			Data: `{"hello": "world"}`,
		},
	)
	if err != nil {
		panic(err)
	}

	engineConf := graphql.NewEngineV2Configuration(schema)
	engineConf.SetDataSources([]plan.DataSource{
		dsCfg,
	})
	engineConf.SetFieldConfigurations([]plan.FieldConfiguration{
		{
			TypeName:  "Query",
			FieldName: "hello",
		},
	})

	ctx := context.Background()
	logger := abstractlogger.NoopLogger

	engine, err := graphql.NewExecutionEngineV2(ctx, logger, engineConf)
	if err != nil {
		panic(err)
	}

	req := graphql.Request{
		Query: "{hello}",
	}

	writer := graphql.NewEngineResultWriter()
	err = engine.Execute(ctx, &req, &writer)
	if err != nil {
		panic(err)
	}

	result := writer.String()
	println(result)
}
```

And it works!

```json
{"data":{"hello":"world"}}
```

A few questions:
1. This approach seems a lot simpler than the one in the tutorial.  Which is preferred? Are there pros/cons to either approach?
2. What is it about this approach that works, while the other one doesn't?
3. I notice I can remove the call to `engineConf.SetFieldConfigurations` entirely, and everything still works.  Is that just because it's using default field configurations and the root nodes configuration of the data source metadata?  (I'm a bit confused why I need both.)
4. I presume these are just growing pains and related to still being in RC status.  Is there a roadmap/timeline to release? I'm not sure if I can consider v2 production-ready, or if I should stick to v1?


Thanks.

**Comment by jensneuse** [comment]
1. both approaches are fine, you usually use default field mapping with GraphQL data sources and disable it for everything else
2. not exactly sure tbh, I don't have the time to deeply investigate your config
3. it's because default config is off and no nesting
4. v2 is used in production heavily, but we don't manually use these low-level APIs. If you're interested to learn how we use the "engine" ourselves, check out [Cosmo Router](https://github.com/wundergraph/cosmo/tree/main/router)

**Comment by mattjohnsonpint** [comment]
Closing this because I've figured out how to use the `execution/engine` package instead.  It mostly works great.  If y'all find some time, you should update your readme tutorial to demonstrate using it.  😃
