### ISSUE TITLE
How to set resolver options on execution engine?

### ISSUE THREAD

**Issue by mattjohnsonpint** [wundergraph/graphql-go-tools#775]
When using `"github.com/wundergraph/graphql-go-tools/execution/engine"`, I can create an engine using [`engine.NewExecutionEngine(ctx, logger, engineConfig)`](https://github.com/wundergraph/graphql-go-tools/blob/a5276d9e1228aa0093eb2e3f3190cca5690e0586/execution/engine/execution_engine.go#L107)

That function sets the resolver options as follows:

https://github.com/wundergraph/graphql-go-tools/blob/a5276d9e1228aa0093eb2e3f3190cca5690e0586/execution/engine/execution_engine.go#L135-L137

How can I set other resolver options, such as `PropagateSubgraphErrors` ?  The options don't appear to be exposed anywhere.

Thanks.

**Comment by jensneuse** [comment]
Fixed with #777
