### ISSUE TITLE
Datasource selection issue when multiple @key exists in subgraphs

### ISSUE THREAD

**Issue by jiajun-brex** [wundergraph/graphql-go-tools#814]
Hello, found an issue when testing cosmo router, and I traced down to a potential bug in dataSource selection in planning. Consider the following 3 subgraph.
A:
```
type Query {
  account: Account
}
type Account {
  user: User
}
type User @key(fields: "id", resolvable: false) {
  id: Int
}
```
B:

```
type User @key(fields: "id") @key(fields: "age") {
   id: Int
   age: Int
}
```
C:
```
type User @key(fields: "age", resolvable: false) {
    age: Int
}
```
And a query
```
query {
  account {
	user {
		id
		age
	}
    }
}
```

The router planning will fail sometimes depending on the order of subgraph in the router config. Upon looking, I found it seems an issue in selecting data sources for the path. It's not consistently selecting B in this case, and will select C if C appears first in the data sources list.

Probably in issue in datasource_filter_visitor, so I added the following unit tests in datasource_filter_visitor_test.go, and it's not consistently selecting 22, sometimes it will select the 33, seems to be random.
```
		{
			Description: "Data source with double key",
			Definition: `
				type Query {
					account: Account	
				}
				type Account {
					user: User
				}
				type User {
					id: Int
					age: Int
				}
			`,
			Query: `
				query {
					account {
						user {
							id
							age
						}
					}
				}
			`,
			DataSources: []DataSource{
				dsb().Hash(11).Schema(`
					type Query {
						account: Account
					}
					type Account {
						user: User
					}
					type User @key(fields: "id", resolvable: false) {
						id: Int
					}
				`).RootNode("Query", "account").RootNode("Account", "user").RootNode("User", "id").DS(),
				dsb().Hash(22).Schema(`
					type User @key(fields: "id") @key(fields: "age") {
						id: Int
						age: Int
					}
				`).RootNode("User", "id", "age").DS(),
				dsb().Hash(33).Schema(`
					type User @key(fields: "age", resolvable: false) {
						age: Int
					}
				`).RootNode("User", "age").DS(),
			},
			ExpectedSuggestions: newNodeSuggestions([]NodeSuggestion{
				{TypeName: "Query", FieldName: "account", DataSourceHash: 11, Path: "query.account", ParentPath: "query", IsRootNode: true, Selected: true, SelectionReasons: []string{"stage1: unique"}},
				{TypeName: "Account", FieldName: "user", DataSourceHash: 11, Path: "query.account.user", ParentPath: "query.account", IsRootNode: true, Selected: true, SelectionReasons: []string{"stage1: unique"}},
				{TypeName: "User", FieldName: "id", DataSourceHash: 22, Path: "query.account.user.id", ParentPath: "query.account.user", IsRootNode: true, Selected: true, SelectionReasons: []string{"stage1: unique"}},
				{TypeName: "User", FieldName: "age", DataSourceHash: 22, Path: "query.account.user.age", ParentPath: "query.account.user", IsRootNode: true, Selected: true, SelectionReasons: []string{"i am not sure what this should be"}},
			}),
		}
```

**Comment by jiajun-brex** [comment]
Also, if B has more fields, and the query has those fields, it will work. It's only when it **only** selects those two @keys fields will make it fail

**Comment by devsergiy** [comment]
Hi @jiajun-brex 

I will suggest to submit a report with original schemas and queries

In example which you currently provided, you probably have in mind that subgraph C has more fields, but as User is not used in any queries and it has no reference resolver it simply makes in inaccessible - which will be a composition error

Regarding unit test - this tests in case you have provided one expected variant of suggestion will randomize order of supplied datasources, which results in randomly selected nodes depending on the supplied datasource order.
Nodes with resolvable false, should get LessPreferable property set, which is possible in case you supply federation configuration to the datasource

Planning is a complicated topic

Thanks,
Wundergraph Team

**Comment by jiajun-brex** [comment]
Thank you for your response, it's certainly a complicated logic. Sharing our schema isn't that helpful because it contains a log of unrelated stuff. Though I created a more complete example with a fork below so you can easily try https://github.com/jiajun-brex/cosmo-multi-key-issue.

I composed a full router config in [here](https://github.com/jiajun-brex/cosmo-multi-key-issue/blob/main/example-schemas/schema.json), I haven't create the subgraph server themselves because it's irrelevant as it fails in planning before it sends the query

I created a router config which points to the above schema. You can start the server by `make dev` in /router
Then, sending the following query to localhost:3002/graphql
```
query MyQuery {
  account {
    user {
      age
      id
    }
  }
}
```
You can see if failed with 
```
{
  "errors": [
    {
      "message": "internal server error"
    }
  ],
  "data": null
}
```
with logs 
`13:56:57 PM ERROR internal error {"component": "@wundergraph/router", "service_version": "dev", "reqId": "C02G311LMD6R/iWb0Uw3Huh-000002", "error": "1 error occurred:\n\t* bad datasource configuration - could not plan the operation. missing path: [query.account.user.age]\n\n"}`

However, it should be able to plan, and sending to subgraph.

 If you actually send the following query
```
query MyQuery {
  account {
    user {
      id
      age
      salary
    }
  }
}
```
It will work pass the planning phase and and fail with "message": "Failed to fetch from Subgraph '0' at Path 'query'.")
This seems to indicating it's selecting the wrong data source and not be able to work.

Another thing I noticed is if you just change the order of composition, and put the actual subgraph that should resolve everything first, ( composed this https://github.com/jiajun-brex/cosmo-multi-key-issue/blob/main/example-schemas/schema-user-first.json) everything will work, because it's likely selecting the user subgraph as the data source to resolve, but this dependency on the order of composition seems wrong, it should reliably select the subgraph that can resolve to resolve

Hopefully this is enough for you to see the problem, let me know if I missed anything

**Comment by Aenimus** [comment]
Please can you test with with router [0.90.2](https://github.com/wundergraph/cosmo/releases/tag/router%400.90.2)?

**Comment by Aenimus** [comment]
@jiajun-brex 
Please can you test with with router [0.90.2](https://github.com/wundergraph/cosmo/releases/tag/router%400.90.2)?

**Comment by Aenimus** [comment]
Also @jiajun-brex, it would be appreciated if you could send cosmo issues to https://github.com/wundergraph/cosmo/issues in the future. 🙏

**Comment by jiajun-brex** [comment]
Thanks for the quick fix, it's working now.! (Will submit issues to cosmo in the future, it's just for this one initially I wasn't sure whether it's an issue in cosmo or graphql-go-tools)
