### ISSUE TITLE
Clarification on V1 vs V2

### ISSUE THREAD

**Issue by empresscor07** [wundergraph/graphql-go-tools#848]
I see that it is suggested that library users migrate to V2 instead of V1. Can I please get clarification on which packages are considered part of V1? 

Specifically my confusion lies with the packages in the [/execution](https://github.com/wundergraph/graphql-go-tools/tree/master/execution) directory. There seem to be packages with the same names inside the V1 [/pkg](https://github.com/wundergraph/graphql-go-tools/tree/master/pkg) directory and the` /execution` directory that don’t exist in the V2 [/pkg](https://github.com/wundergraph/graphql-go-tools/tree/master/v2/pkg) directory. (Example - the `graphql` package and the `gateway` package). 

Are the packages inside the `/execution` directory part of V2 or are they deprecated?

**Comment by devsergiy** [comment]
Hi @empresscor07 

In v1 we had execution and graphql wrappers embedded in the main package as there were no external dependencies.

With v2, the engine needs external configuration coming from [cosmo composition](https://github.com/wundergraph/cosmo/tree/main/composition)

The execution package uses composition to create the configuration for the v2 engine, so to make sure that we do not have cross-dependencies and to have a smaller binary size of an engine - we have extracted execution and graphql packages into a separate package depending on both composition and v2

Given that the state of the packages is next


|package|state|depends on|
|-------|-----|------------|
|graphql-go-tools v1|deprecated, maintenance mode|-|
|graphql-go-tools v2|actual version, active development|-|
|execution|actual version|depends on v2 and composition|
|examples/federation|actual example|depends on execution package|

Thanks,
Wundergraph Team

**Comment by empresscor07** [comment]
Ok thank you - that makes a lot of sense. The confusion I had at first stemmed from [issue 827](https://github.com/wundergraph/graphql-go-tools/issues/827) where the author was asking for a V2 example and links to the `examples/federation` package referring to it as V1 (and is not corrected in the response).

It is very helpful to know that the `execution` and `examples/federation` packages are current and not deprecated.

**Comment by empresscor07** [comment]
Meant to close as completed.
