### ISSUE TITLE
Compile error - need a new version tag for execution

### ISSUE THREAD

**Issue by mattjohnsonpint** [wundergraph/graphql-go-tools#857]
Hi.  Just like before with #812, once again we've got a compatibility mismatch.

go.mod:
```
require(
	github.com/wundergraph/graphql-go-tools/execution v1.0.3
	github.com/wundergraph/graphql-go-tools/v2 v2.0.0-rc.65
)
```

build output:
```
# github.com/wundergraph/graphql-go-tools/execution/engine
../../../go/pkg/mod/github.com/wundergraph/graphql-go-tools/execution@v1.0.3/engine/execution_engine.go:197:9: assignment mismatch: 1 variable but e.resolver.ResolveGraphQLResponse returns 2 values
```

Looks like #854 broke compatibility.

Can you publish a `execution/v1.0.4` tag please?

I can work around it in the interim with:

go.mod:
```
require(
	github.com/wundergraph/graphql-go-tools/execution v1.0.4-0.20240723104837-8b3266e8dd60
	github.com/wundergraph/graphql-go-tools/v2 v2.0.0-rc.65
)
```

Thanks.

**Comment by devsergiy** [comment]
Hi @mattjohnsonpint 

Here you are https://github.com/wundergraph/graphql-go-tools/releases/tag/execution%2Fv1.0.4

**Comment by mattjohnsonpint** [comment]
@devsergiy - it happened again with 2.0.0-rc.69.  Now we need execution 1.0.5.  Do you want me to keep opening issues for this?  Any way to improve your internal process to prevent these?  Maybe a CI job that builds them together?
