### ISSUE TITLE
Issue when trying to resolve implementation type of interface when a field does not exist

### ISSUE THREAD

**Issue by hmajid2301** [wundergraph/graphql-go-tools#866]
Hi :wave:,

I think I have come across a bug in this library (please let me know if I am missing something and this is not the case).

Example Repository: https://gitlab.com/haseeb.majid1/graphql-minimal

**TL;DR;**

The bug seems to occur when I have an interface, and it is implemented and then extended by another service. If we try to fetch a field which was extended, but there is no data exists which includes that field.

We get an error `Get \"\": unsupported protocol scheme \"\"`.

## Version

```
 github.com/wundergraph/graphql-go-tools v1.67.2
```

## Background

The repository, linked above, creates a minimal example to try to replicate a bug. I am noticing occurs with service(s) when I use federation.

## Explanation

Let's have a look at an example, which may better explain the issue we are noticing (in this repository).

> NOTE: When I say graphql gateway this is the service I built which uses this library.

In this example defined in `servicea`:

```graphql
extend type Query {
  # ...
  randomItem: UserItem
}

interface UserItem {
  id: ID!
}
```

Then we have several implementations of that interface defined like so:

```graphql
type UserItemA implements UserItem @key(fields: "id userID") {
  id: ID!
  userID: ID!
  actionA: String!
}

type UserItemB implements UserItem @key(fields: "id userID") {
  id: ID!
  userID: ID!
  actionB: String!
}
```

Then in another service, say `serviceb`, we extend one of these implementations like so:

```graphql
extend type UserItemA @key(fields: "id userID") {
  id: ID! @external
  userID: ID! @external
  reason: ID!
}
```

If we send a query to see which types exist:

```graphql
query MyQuery1 {
  randomItems {
    __typename
  }
}
```

Which returns:

```json
{
  "data": {
    "randomItem": {
      "__typename": "UserItemB"
    }
  }
}
```

As we can see, we only have types of `UserItemB`. When we send a query to get the `reason`:

```graphql
query MyQuery2 {
  randomItems {
    ... on UserItemA {
      reason
    }
  }
}
```

This is when the error is thrown by the GraphQL gateway. Where this library is used. Looking at the error thrown by the GraphQL gateway (which is using this library) I see:

```bash
Get \"\": unsupported protocol scheme \"\"
```

Where the error is thrown when we call `Execute` function on `ExecutionEngineV2`. The relevant code in our GraphQL gateway looks like so (this is HTTP handler function):

```go
var gqlRequest graphql.Request
if err := graphql.UnmarshalHttpRequest(r, &gqlRequest); err != nil {
    // handle error
}

// ...
resultWriter := graphql.NewEngineResultWriterFromBuffer(buf)
err := g.engine.Execute(r.Context(), &gqlRequest, &resultWriter, graphql.WithAdditionalHttpHeaders(headers))
// ...
```

Where the engine is of type:

```go
engine         *graphql.ExecutionEngineV2
```

### Code in Library

From what I can see, the error happens within the method `resolveObject` in `pkg/engine/resolve/resolve.go`.
I noticed that this part (the error, and a null is returned) of the code is being called `pkg/engine/resolve/inputtemplate.go` in the `Render` method.

```go
if errors.Is(err, setTemplateOutputNull) {
    preparedInput.Reset()
    preparedInput.WriteBytes(literal.NULL)
    return nil
}
```

Where the error is set in this case:

```go
case ObjectVariableKind:
    err = i.renderObjectVariable(ctx.Context(), data, segment, preparedInput)
```

## Reproduce

1. Start up both services in this repository

```bash
cd servicea
PORT=8095 go run server.go

# In another terminal

cd serviceb
PORT=8096 go run server.go
```

2. Point your GraphQL gateway to these services, i.e. `http://localhost:8095/query`, to enable federation.
3. Go to a GraphQL playground and run this query

```graphql
query MyQuery2 {
  randomItem {
    ... on UserItemA {
      reason
    }
  }
}
```

4. You should see this error from the output of the GraphQL gateway:

```bash
Get \"\": unsupported protocol scheme \"\"
```

Please let me know if you need additional information! Happy to help where I can.

Thanks

**Comment by devsergiy** [comment]
Hi @hmajid2301 

`v1.67.2` is no longer maintained version

Please try [v2.0.0-rc.68](https://github.com/wundergraph/graphql-go-tools/releases/tag/v2.0.0-rc.68)

With this [example](https://github.com/wundergraph/graphql-go-tools/tree/master/examples/federation)

**Comment by hmajid2301** [comment]
Okay, thanks, I will try to do that next week and see if that resolves the issue.

**Comment by hmajid2301** [comment]
I think this resolved it, I'm hitting other issues now :thinking: (around http headers). But this looks to be working.
