### ISSUE TITLE
GraphQL cache proxy usage

### ISSUE THREAD

**Issue by Winfle** [wundergraph/graphql-go-tools#868]
Hello, guys.
First of all, I would like to thank to all contributors for the project.
You're doing awesome work!

This is not an issue, I just investigating future project concept.
One of ideas was to create a GraphQL cache proxy based on queries entities.
So, we analyze types inside and fetch fetch for each of them if exist.

My question is, how does graphql-go-tools fits into this?
Thanks

**Comment by AndreasZeissner** [comment]
This sounds like fascinating idea. We would like to see how it evolves.
