### ISSUE TITLE
How to pass http headers to sub-graphs (services)

### ISSUE THREAD

**Issue by hmajid2301** [wundergraph/graphql-go-tools#886]
Hi all,

I am currently trying to work out how I can forward HTTP headers from my gateway service to the sub-graphs. I
currently have a method which looks something like this, which takes in some data sources, i.e. sub-graphs and returns a slice
of graphql_datasource configurations:

```go
func (g *Gateway) createDataSourceConfig(datasources []entities.ServiceDataSource) ([]graphql_datasource.Configuration, error) {
	dataSourceConfigs := make([]graphql_datasource.Configuration, 0, len(datasources))

	for _, datasource := range datasources {
		schemaConfig, err := graphql_datasource.NewSchemaConfiguration(datasource.SDL, &graphql_datasource.FederationConfiguration{
			Enabled:    true,
			ServiceSDL: datasource.SDL,
		})
		if err != nil {
			return nil, err
		}

		dataSourceConfig, err := graphql_datasource.NewConfiguration(graphql_datasource.ConfigurationInput{
			Fetch: &graphql_datasource.FetchConfiguration{
				URL:    datasource.URL,
				Method: http.MethodPost,
				Header: http.Header{
					httpHeaderAuthorization:           []string{fmt.Sprintf("{{ .request.headers.%s }}", httpHeaderAuthorization)},
				},
			},

			SchemaConfiguration: schemaConfig,
		})
		if err != nil {
			return nil, err
		}

		dataSourceConfigs = append(dataSourceConfigs, dataSourceConfig)
	}

	return dataSourceConfigs, nil
}
```

I tried to look at some tests in the code:

- https://github.com/wundergraph/graphql-go-tools/blob/master/v2/pkg/engine/datasource/graphql_datasource/graphql_datasource_test.go#L302-L311
- https://github.com/wundergraph/graphql-go-tools/blob/master/execution/engine/execution_engine_test.go#L1807-L1905

Any help would be greatly appreciated. Please let me know if you need more details, I am sure I am missing something.

Relevant comment?: https://github.com/wundergraph/graphql-go-tools/issues/459#issuecomment-1336936796

Thanks

**Comment by jensneuse** [comment]
This approach can be used: https://github.com/wundergraph/graphql-go-tools/issues/383#issuecomment-2345548204

Out of curiosity, what prevents you from using Cosmo Router?

**Comment by hmajid2301** [comment]
> Out of curiosity, what prevents you from using Cosmo Router?

Perhaps I misunderstood what the Router is, but I really only know Go very well. So I think it'd be easier of me to write code in a language I know.

I looked at your examples. I have stuff setup slightly differently (correct me if I'm wrong):

```go
err := g.engine.Execute(r.Context(), &gqlRequest, &resultWriter, engine.WithAdditionalHttpHeaders(headers))
```

From reading the code in the addiontal headers functional option. Does it do the same thing as the code you shared creating the resolver context? :thinking:

**Comment by StarpTech** [comment]
The router is written in Go and can be extended with Go. The functionality you are asking for is already implemented and can be configured through configuration. https://cosmo-docs.wundergraph.com/router/proxy-capabilities
