### ISSUE TITLE
Higher CPU-usage after epoll implementation

### ISSUE THREAD

**Issue by argoyle** [wundergraph/graphql-go-tools#940]
The new epoll implementation introduced in rc110 increased the CPU-usage quite drastically (my horizontal pod autoscaler was running on max replicas). Reverting back to rc109 puts it back to normal again. Feels like a busy-loop somewhere.

**Comment by jensneuse** [comment]
Please try 111

**Comment by argoyle** [comment]
kubectl top pod output
rc109:
<img width="578" alt="image" src="https://github.com/user-attachments/assets/2a4d429f-4ee9-43d2-91a3-e8ac8b6ad354">
rc111:
<img width="574" alt="image" src="https://github.com/user-attachments/assets/01fb036b-75cb-4031-9770-b61f32793189">

**Comment by jensneuse** [comment]
Can you explain the screenshots? I don't know much about kubectl output, sorry.

**Comment by argoyle** [comment]
Sorry. 😁 The column with increased numbers is the CPU usage. As you can see there is a 15-20 times increase in CPU at rest. And my autoscaler has decided to scale up to 4 replicas instead of my regular 2.

**Comment by jensneuse** [comment]
Please try 112

**Comment by argoyle** [comment]
Better but still a bit higher, about 10 times 109 now: 
<img width="566" alt="image" src="https://github.com/user-attachments/assets/354aac04-6280-42b6-9652-b2453900b270">

**Comment by jensneuse** [comment]
Numbers look like 109 or am I misinterpreting it?

**Comment by argoyle** [comment]
109 is on 1m, 111 on 25-30m and 112 on 10-15m so still some way off I would say.

**Comment by jensneuse** [comment]
Oh, I was looking at Mi, is that Mibibytes memory usage? I have an idea how we can make it 1.

**Comment by argoyle** [comment]
Correct, that's mem-usage. That's been quite constant.

**Comment by jensneuse** [comment]
Please test 113 and let me know if it looks fine.

**Comment by argoyle** [comment]
That did the trick. Back down to 1 now. Thanks for quick resolution. ❤️
